### ISSUE TITLE
Help return list of Movies ([]domain.Movie) back to gRPC repeated object

### ISSUE THREAD

**Issue by AntonyIS** [AntonyIS/go-grpc-crud#1]
```
func (s *Server) GetMovies(ctx context.Context, in *pb.EmptyRequest) (*pb.MovieListResponse, error) {

	db, err := repo.NewPostgresRepository()

	if err != nil {
		return nil, nil
	}
       //Get all movies from the database
	movies, err := db.GetMovies()

	if err != nil {
		return &pb.MovieListResponse{}, status.Error(404, "movies not found")
	}
       //Error : cant return slice of movie back to gRPC
	return &pb.MovieListResponse{Movies: movies}, nil

}

//proto file

service MovieService{
    rpc CreateMovie(MovieRequest) returns (MovieResponse) {}
    rpc GetMovie(MovieID) returns (MovieResponse) {}
    rpc GetMovies(EmptyRequest) returns (MovieListResponse) {}
    rpc UpdateMovie(MovieRequest) returns (MovieResponse) {}
    rpc DeleteMovie(MovieID) returns (Message) {}
}

message MovieRequest {
    string id = 1;
	string name = 2;
	string description=3;
	string release_date= 4;
	string image = 5;
}

message MovieResponse {
    string id = 1;
	string name = 2;
	string description=3;
	string release_date= 4;
	string image = 5;
}
message MovieListResponse {
    repeated MovieResponse movies = 2;
}
```

**Comment by MwinyiMoha** [comment]
In this scenario, the `Movies` would be a slice of `pb.MovieResponse`.  You could do something like:
```
var movieResponse := []pb.MovieResponse{}
for _, movie := range movies {
    movieResponse = append(movieResponse, &pb.MovieResponse{ *fields go here* })
}

return &pb.MovieListResponse{Movies: &movieResponse}, nil
```

**Comment by AntonyIS** [comment]
aha . thank you @MwinyiMoha , let me try that one out.

**Comment by AntonyIS** [comment]
@MwinyiMoha , this worked. Thanks.I thought there could be a way of returning a list/slice to grpc **MovieListResponse** without iterating. 
In a situation where we have many records, it will take time looping through values costing O(n) or even O(n2) for embedded entitiies([]movies struct with say []Actors struct.) What are your thoughts on that?

**Comment by MwinyiMoha** [comment]
Yes, it's true that iteration would be costly in this situation. Database drivers usually have helper functions around this. For example with mongodb you can do:
```
var objList := make([]domain.Model, 0)

cursor, err := collection.Find(ctx, bson.M{}, findOptions)
\\ handle error here

err := cursor.All(ctx, &objList)
\\ handle error here
```
Basically, `cursor.All` maps the documents matched by the find query into a list of objects in a performant way. I haven't used postgres with Go that much to come across such functionality but I am sure there should be. Let's check documentation around cursors in postgres.

**Comment by AntonyIS** [comment]
Yes sure @MwinyiMoha . Thank you once again.

**Comment by AntonyIS** [comment]
This has been resolved with @MwinyiMoha help.
